[package]
name = "yurt"
version = "0.2.0"
authors = ["Julian Thomassie <julianthomassie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
clap = { version = "3.0.7", features = ["cargo"] }
dirs = "4.0.0"
env_logger = "0.9.0"
git2 = "0.13.22"
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.5.4"
reqwest = { version = "0.11.4", features = ["blocking"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
symlink = "0.1.0"
whoami = "1.1.3"

[dev-dependencies]
pretty_assertions = "1.2.1"
tempfile = "3.2.0"

[profile.release]
debug = true
