[package]
name = "dots"
version = "0.1.0"
authors = ["Julian Thomassie <julianthomassie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
git2 = "0.13.20"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
shellexpand = "2.1.0"
symlink = "0.1.0"
tempfile = "3.2.0"
whoami = "1.1.2"
