[package]
name = "yurt"
version = "0.2.0"
authors = ["Julian Thomassie <julianthomassie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
dirs = "3.0"
env_logger = "0.9"
git2 = "0.13"
lazy_static = "1.4"
log = "0.4"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
symlink = "0.1"
tempfile = "3.2"
whoami = "1.1"
