[package]
name = "yurt"
version = "0.3.0"
authors = ["Julian Thomassie <julianthomassie@gmail.com>"]
repository = "https://github.com/jcthomassie/yurt"
description = "Simple CLI tool for dotfile management."
readme = "README.md"
license-file = "LICENSE"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.8", features = ["cargo"] }
dirs = "4.0.0"
env_logger = "0.9.0"
git2 = "0.14.2"
lazy_static = "1.4.0"
log = "0.4.16"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["blocking"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
symlink = "0.1.0"
whoami = "1.2.1"

[dev-dependencies]
pretty_assertions = "1.2.1"
tempfile = "3.3.0"

[profile.release]
strip = "symbols"
