---
name: build

on:
  release:
    action: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/<name>
            asset_name: <name>-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/<name>.exe
            asset_name: <name>-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/<name>
            asset_name: <name>-macos

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build binaries
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
