---
name: docs

on:
  push:
    branches: [ main, docs ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Cargo doc
        run: cargo doc --no-deps

      - name: Remove target/doc/.lock
        run: rm target/doc/.lock
      - name: Redirect to target/doc/index.html
        run: echo '<meta http-equiv="refresh" content="0;url=yurt/index.html">' > target/doc/index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
