---
name: tests

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/tests.yaml"
      - "src/**"
      - "test/**"
      - "Cargo.*"

  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/tests.yaml"
      - "src/**"
      - "test/**"
      - "Cargo.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1

      - name: Cargo check
        run: cargo check --verbose

      - name: Cargo test
        run: cargo test --verbose

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings
